version: "3.7"
services:

  pyplayground:
    image: python:3.11
    container_name: pyplayground
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ALL_PROXY: "http://host.docker.internal:7890"
    volumes:
      - .:/opt/pyplayground
    command: tail -f /dev/null 
